"""Enumerated values accepted by the TMS Gateway API.

Mirrors the enums exposed by the gateway resource models so the CLI can offer
pick lists without hard-coding strings in several places.
"""

SHIPMENT_STATUSES = ["BUILDING", "BOOKED", "CANCELED", "OFFERED", "REQUESTED"]

# Statuses the gateway accepts on create/update.
WRITABLE_SHIPMENT_STATUSES = ["BUILDING", "BOOKED", "REQUESTED"]

MODES = ["LTL", "FTL", "AIR", "EXPEDITED", "PARCEL", "FCL", "LCL", "COURIER"]

EQUIPMENT_TYPES = [
    "LTL_DRY_VAN",
    "FTL_FLAT_BED",
    "FTL_STEP_DECK",
    "FTL_REMOVABLE_GOOSENECK",
    "FTL_HOT_SHOT",
    "FTL_REEFER",
    "FTL_CONESTOGA",
    "FTL_BOX_TRUCK",
    "FTL_DRY_VAN",
    "FTL_VAN_WITH_HAZMAT",
    "FTL_VAN_WITH_TANKER",
    "FTL_VAN_WITH_TANKER_AND_HAZMAT",
    "ET_FTL_BULK",
    "ET_FTL_INTERMODAL",
    "ET_FTL_PARTIAL",
    "ET_FTL_PICKUP_TRUCK",
    "ET_FTL_POWER_ONLY",
    "ET_FTL_REEFER_HAZMAT",
    "ET_FTL_SPRINTER_VAN",
]

LTL_EQUIPMENT_TYPES = ["LTL_DRY_VAN"]

FTL_EQUIPMENT_TYPES = [value for value in EQUIPMENT_TYPES if value not in LTL_EQUIPMENT_TYPES]

SERVICE_LEVELS = [
    "STANDARD",
    "GUARANTEED",
    "GUARANTEED_1030",
    "GUARANTEED_1200",
    "GUARANTEED_1500",
    "GUARANTEED_PM",
    "GUARANTEED_1_DAY",
    "GUARANTEED_2_DAY",
]

FREIGHT_CLASSES = [
    "FREIGHT_CLASS_50",
    "FREIGHT_CLASS_55",
    "FREIGHT_CLASS_60",
    "FREIGHT_CLASS_65",
    "FREIGHT_CLASS_70",
    "FREIGHT_CLASS_77_5",
    "FREIGHT_CLASS_85",
    "FREIGHT_CLASS_92_5",
    "FREIGHT_CLASS_100",
    "FREIGHT_CLASS_110",
    "FREIGHT_CLASS_125",
    "FREIGHT_CLASS_150",
    "FREIGHT_CLASS_175",
    "FREIGHT_CLASS_200",
    "FREIGHT_CLASS_250",
    "FREIGHT_CLASS_300",
    "FREIGHT_CLASS_400",
    "FREIGHT_CLASS_500",
]

PACKAGE_TYPES = [
    "PALLETS",
    "BAGS",
    "BARRELS",
    "BOXES",
    "BUNDLES",
    "CANS",
    "CARTONS",
    "CASES",
    "CONTAINERS",
    "CRATES",
    "CYLINDERS",
    "DRUMS",
    "LOOSE",
    "OTHER",
    "PACKAGES",
    "RACKS",
    "ROLLS",
    "SKIDS",
    "TOTES",
    "TRAILERS",
    "TUBES",
]

ACCESSORIAL_TYPES = ["ORIGIN", "DESTINATION", "SHIPMENT", "PRODUCT"]

ORIGIN_ACCESSORIALS = [
    "APPOINTMENT",
    "AIR",
    "CONSTRUCTION",
    "INSIDE",
    "LIFTGATE",
    "LIMITED_ACCESS",
    "NOTIFY",
    "RESIDENTIAL",
    "TRADESHOW",
]

DESTINATION_ACCESSORIALS = list(ORIGIN_ACCESSORIALS)

PRODUCT_ACCESSORIALS = ["PROTECT_FROM_FREEZE", "HAZARDOUS_MATERIAL"]

SHIPMENT_ACCESSORIALS = ["COLLECT_ON_DELIVERY", "MARKING", "PREPAY", "SORT_SEGREGATE"]

ACCESSORIALS_BY_TYPE = {
    "ORIGIN": ORIGIN_ACCESSORIALS,
    "DESTINATION": DESTINATION_ACCESSORIALS,
    "PRODUCT": PRODUCT_ACCESSORIALS,
    "SHIPMENT": SHIPMENT_ACCESSORIALS,
}

REFERENCE_NUMBER_TYPES = [
    "PO_NUMBER",
    "SO_NUMBER",
    "PRO_NUMBER",
    "BOL_NUMBER",
    "QUOTE_NUMBER",
    "PUF_NUMBER",
    "PICKUP_NUMBER",
    "SERIAL_NUMBER",
    "GL_CODE",
    "CUSTOMER_NUMBER",
    "SHIPMENT_ID",
    "WAREHOUSE_NUMBER",
    "CTL",
    "MAWB_NUMBER",
    "RETURN_AUTHORIZATION",
    "EXPORT_BOOKING_NUMBER",
    "CONTAINER_NUMBER",
    "IT_NUMBER",
    "SHIPPER_ID",
    "ET_CUSTOM_REFERENCE_1",
    "ET_CUSTOM_REFERENCE_2",
    "ET_CUSTOM_REFERENCE_3",
    "ET_CUSTOM_REFERENCE_4",
    "ET_CUSTOM_REFERENCE_5",
    "ET_CUSTOM_REFERENCE_6",
    "ET_CUSTOM_REFERENCE_7",
    "ET_CUSTOM_REFERENCE_8",
    "ET_CUSTOM_REFERENCE_9",
    "ET_CUSTOM_REFERENCE_10",
]

LOCATION_DIRECTION_TYPES = ["MY_LOCATION", "MY_OTHER_LOCATION", "THIRD_PARTY"]

FREIGHT_TERMS = ["COLLECT", "THIRD_PARTY", "PREPAID"]

SELECTED_REASON_TYPES = [
    "SERVICE_ISSUES",
    "NO_EQUIPMENT",
    "CUSTOMER_SPECIFIED",
    "TRANSIT_TIME",
    "MISSED_PICKUP",
    "ACCESSORIAL_NA",
]

WEIGHT_UNITS_OF_MEASURE = ["LB"]

DIMENSIONS_UNITS_OF_MEASURE = ["IN"]

PALLET_TYPES = ["PALLET_40_40", "PALLET_40_48"]
